### ISSUE TITLE
Theme settings have additional space in UI

### ISSUE THREAD

**Issue by BenParizek** [mildlygeeky/craft_kint#1]
Not a big issue at all, but you can add `first: true` to the form macro on the Theme setting dropdown to make the field fit more nicely in the settings page UI.  
https://github.com/mildlygeeky/craft_kint/blob/master/kint/templates/settings.html

Nice touch with the included themes.  Aante Light is my favorite ;-)

**Comment by mildlygeeky** [comment]
Thanks @BenParizek — didn't know about that option. Just added :)
