### ISSUE TITLE
Consider updating default order of object tabs

### ISSUE THREAD

**Issue by BenParizek** [mildlygeeky/craft_kint#2]
When I use `craft.kint.dd()` in my template on an EntryModel, the order of the Kint tabs presented in the output are:
- Contents
- Available Methods
- Static Class Properties
- Iterator Contents

On first glance, with this scenario, my preferred order would be:
- Iterator Contents
- Available Methods
- Contents
- Static Class Properties

The _Contents_ tab mostly has private and protected properties which I'm unable to interact with.  So I immediately have to select another tab.  The _Static Class Properties_ tab also doesn't have anything I can interact with easily, so while I don't mind the info provided by these tabs, it seems the best place for them is farther down the list of tabs so I don't have to take an extra step each time.

The remaining two tabs are quite handy. _Iterator Contents_ provides a list of things I can immediately interact with in the loop.  (I wish the name was a bit more user friendly, but I feel that's true most of the time with everything).  And _Available Methods_ provides several public methods I could use or consider using.

Not sure if it is possible, or desirable for everyone, but my vote would be to prioritize the _Iterator Contents_ and _Available Methods_ tabs as I could see them coming in handy more often than the other tabs while debugging.

**Comment by bossanova808** [comment]
A very big :+1: for this as well if possible.  All the interested stuff is on the iterator contents tab.

**Comment by mildlygeeky** [comment]
This would be tricky — right now the custom parsers get pulled in alphabetically based on their script name, and the "contents" tab is pretty well planted as the first item in the less-than-easy to read code. I'm leaving this open for now, but don't expect it to be altered too quickly.

**Comment by BenParizek** [comment]
Figured it might be a bit tricky.  I just took a stab at doing this with javascript in the browser console, if doing this in javascript after the fact is even an appropriate angle to consider.  The following code takes the final output and just rearranges the tabs after they are output on the page.  This was tested with a dump of the Entry model in a Twig template so there are likely some scenarios I might not be taking into account, and javascript isn't my strong suit so it could potentially be improved too. 

```
allTabs = document.getElementsByClassName("kint-tabs");

navContainer = allTabs[0];
oldNavTabs = navContainer.childNodes;

infoContainer = navContainer.nextSibling;
oldTabInfo = infoContainer.childNodes;

var newNavTabs = [];
newNavTabs[0] = oldNavTabs[3];
newNavTabs[1] = oldNavTabs[1];
newNavTabs[2] = oldNavTabs[0];
newNavTabs[3] = oldNavTabs[2];

newNavTabs[0].className = 'kint-active-tab';
newNavTabs[2].className = '';

var newTabInfo = [];
newTabInfo[0] = oldTabInfo[3];
newTabInfo[1] = oldTabInfo[1];
newTabInfo[2] = oldTabInfo[0];
newTabInfo[3] = oldTabInfo[2];

while ( oldNavTabs.firstChild ) {
  oldNavTabs.removeChild( oldNavTabs.firstChild );
}

for (i = 0; i < newNavTabs.length; i++) {
    navContainer.appendChild(newNavTabs[i]);
    infoContainer.appendChild(newTabInfo[i]);
}
```

**Comment by mildlygeeky** [comment]
Part of the issue, though, is that there are many different options that can be exposed, though the above tabs are the most common. If you called Kint via PHP and passed in JSON or XML, or even a hes value, you'd get different tabs. Need to think through this a bit more.
