### ISSUE TITLE
Consider making variables into Twig functions

### ISSUE THREAD

**Issue by BenParizek** [mildlygeeky/craft_kint#3]
Currently, we can use the kint plugin on template variables like so:

`{{ craft.kint.dd(entry) }}`

It would be possible to shorten that a good bit by updating the variables to be Twig functions instead:

`{{ dd(entry) }}`

**Comment by bossanova808** [comment]
- 1 for this

**Comment by mildlygeeky** [comment]
Thanks — just taught myself how to write them, and added them into version 1.1.0 which is now available. :)
